# HOW TO USE AIRBNB STYLE GUIDE
#
# 1. Install 'ESLint' plugin on VSCode
# 2. Install following npm packages locally
#    yarn add babel-eslint eslint eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y
# 3. add script
#    "prettier": "prettier --write \"src/**/*.{js,jsx,css}\"",

# HOW TO USE PRETTIER
#
# 1. add following packages
#    prettier eslint-config-prettier eslint-plugin-prettier
# 2. add .eslintrc.yml
# 3. add a following script into package.json
#    "prettier": "prettier --write \"src/**/*.{js,jsx,ts,tsx,css}\"",
# 4. add script
#    "lint": "eslint --ext .js,.jsx .",

extends: airbnb
parser: babel-eslint
rules:
  arrow-parens: 0
  function-paren-newline: 0
  import/no-extraneous-dependencies: 0
  jsx-a11y/anchor-is-valid:
   - error
   - components:
      - Link
     specialLink:
      - to
  linebreak-style: 0
  no-underscore-dangle: 0
  object-curly-newline: 0
  prettier/prettier: 2

env:
  mocha: true

plugins:
  - prettier

# stop no-undef warning about global variables.
globals:
  document: true
  window: true
  graphql: true
